env:
  RUBY_VERSION: 2.7.6

on:
  push:
    branches:
      - '**'
      
jobs:
  # LINTERS
  linters_ruby:
    name: Linters Ruby
    runs-on: ubuntu-latest
    env:  
      BUNDLE_GEMFILE: "/home/runner/work/test-actions/"
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Formatting and Security Checks
        run: |
          bundle exec rubocop
